In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'D:\Recess\MusaMaliDerick\Lectures\week4\Morning_DataScience\EstateFile.csv')

print(df.head())

      price  area  bedrooms  bathrooms  stories  parking
0  13300000  7420         4          2        3        2
1  12250000  8960         4          4        4        3
2  12250000  9960         3          2        2        2
3  12215000  7500         4          2        2        3
4  11410000  7420         4          1        2        2

In [3]:
#Calculates the maximum absolute value for each column.
max_abs = np.max(np.abs(df),axis=0)
print(max_abs)

price        13300000
area             9960
bedrooms            4
bathrooms           4
stories             4
parking             3
dtype: int64

In [ ]:
#Divides each value by the maximum absolute value of its column to scale the data.
scaled_df = df/ max_abs

print(scaled_df)

#scaled_df.head(): Displays the first few rows of the scaled dataset.
scaled_df.head()

      price      area  bedrooms  bathrooms  stories   parking
0  1.000000  0.744980      1.00       0.50     0.75  0.666667
1  0.921053  0.899598      1.00       1.00     1.00  1.000000
2  0.921053  1.000000      0.75       0.50     0.50  0.666667
3  0.918421  0.753012      1.00       0.50     0.50  1.000000
4  0.857895  0.744980      1.00       0.25     0.50  0.666667
5  0.815789  0.853414      0.75       0.75     0.75  0.666667
6  0.763158  0.903614      1.00       0.50     0.75  1.000000
7  0.736842  0.652610      0.75       0.50     0.50  0.333333
8  0.714286  0.722892      0.75       0.25     0.25  0.333333
9  0.691729  0.682731      1.00       0.50     0.50  0.666667

      price      area  bedrooms  bathrooms  stories   parking
0  1.000000  0.744980      1.00       0.50     0.75  0.666667
1  0.921053  0.899598      1.00       1.00     1.00  1.000000
2  0.921053  1.000000      0.75       0.50     0.50  0.666667
3  0.918421  0.753012      1.00       0.50     0.50  1.000000
4  0.857895  0.744980      1.00       0.25     0.50  0.666667

In [7]:
#Min-Max Scaling
#Min-Max Scaling rescales features by subtracting the minimum value and dividing by the difference between the maximum and minimum values. 
# This usually maps feature values to the range 0 to 1 while preserving the original distribution.

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

scaled_df.head()

      price      area  bedrooms  bathrooms   stories  parking
0  1.000000  0.265896       1.0   0.333333  0.666667      0.5
1  0.743902  0.710983       1.0   1.000000  1.000000      1.0
2  0.743902  1.000000       0.0   0.333333  0.333333      0.5
3  0.735366  0.289017       1.0   0.333333  0.333333      1.0
4  0.539024  0.265896       1.0   0.000000  0.333333      0.5